@startuml

'hide empty members
hide circle

class bmsActor
class invDrvActor
class pvActor

bmsActor .right.> invDrvActor: <<flow>>\n""INV_DRIVER_*"" events 
pvActor .right.> bmsActor: <<flow>>\n""PV_*"" events

@enduml
