@startuml

cloud "Power grid" as grid
interface "Power\nsocket" as isocket
component "Charge\nController" as chrg
component "Battery" as batt
component "Inverter" as inv
interface "Power\nsocket" as osocket

component "PV power plant" as pv #Green

grid .down. isocket
isocket )- chrg: 230V AC
chrg - batt: DC
batt - inv: DC
inv -( osocket: 230V AC

osocket .up. grid

isocket )-down[#green]- pv

@enduml
