@startuml
skinparam componentStyle uml2

cloud "Power grid" as grid
cloud "WIFI home network" as net
interface "Power\nsocket" as isocket
component "AC Battery" as batt #pink
component "Smartmeter" as sm
component "Battery Management" as mng 
interface "Power\nsocket" as osocket

component "PV power plant" as pv 

grid .down. isocket
isocket )- batt: 230V AC
batt -( osocket: 230V AC
osocket .up. grid

isocket )-down- pv

batt <.down. net: <<flow>>\ncommands
sm .up.> net: <<flow>>\nPV excess\nmeasurement
mng .up.> net: <<flow>>\ncommands
@enduml
